excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://blog.robel.net
title: John Robel's Blog
email: blog@robel.net
tagline: A log of everyday life
description: My awesome new site
paginate: 5
